### PR TITLE
moto thumbs

### PR DESCRIPTION
**Pull request by WizzardSK**

### CODE REVIEW

**Comment by Zlika** [comment]
Hello. Could you please explain your change? It seems to me that all the images have been slightly shrunk, is there a reason for that?

**Comment by WizzardSK** [comment]
I added the images for TOSEC naming database.

**Comment by Zlika** [comment]
Ok, I understand now, someone replaced the old Thomson DAT file (cf. https://github.com/libretro/libretro-database/commit/94fe620446fa4c5bf23a91f853bb6f2e93d15020 ) with the TOSEC version, which uses the name of the file as the name of the game. So now the name of the images must be updated accordingly.
However, why adding new (and smaller) images instead of just renaming the existing files?

**Comment by WizzardSK** [comment]
I just added the new images from screenscraper and resized them to max. 512 or 320 px. I did not notice the original images are smaller in file size. Hope it is not a big issue.

**Comment by Zlika** [comment]
I created and used this python script to scrap all the images from screenscraper and then used imagemagick to optimize them: https://github.com/Zlika/libretro-database-thomson/blob/master/scripts/generate_thomson_thumbnails.py
Is there a reason to resize the images to 512 or 320px? If the problem is just the name of the files, it would have been better (on a git point of view) to just rename them.

**Comment by WizzardSK** [comment]
Thanks, I will check that script, it may help with other systems. I used
512px max for boxarts because it is the biggest allowed size for libretro
thumbs. For snaps and titles, when a picture was bigger than 512 px, I
resized to 320. I know, sometimes it even increases the file size. I have
no problem with renaming those files or even just using the symlinks of my
new files pointing to original files.

Or could you run that script again to update the thumbs using current TOSEC database?

**Comment by WizzardSK** [comment]
please, merge :)

**Comment by RobLoach** [comment]
That's a good point. That DAT hasn't been updated in a while. If it's all just the TOSEC files, we could likely leverage the libretro-dats script for them:
https://github.com/RobLoach/libretro-dats/pull/90/files

**Comment by WizzardSK** [comment]
can we merge then?

**Pull request merged**
